services:
  # PostgreSQL with PgVector extension
  postgres:
    image: pgvector/pgvector:pg16
    container_name: appread-postgres
    environment:
      POSTGRES_DB: appread
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend service (Spring Boot)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: appread-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appread
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    volumes:
      - ./temp-repos:/app/temp-repos

volumes:
  postgres-data: